name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test EmployeeHR.LogicTests --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish
        run: dotnet publish EmployeeHR.Api/EmployeeHR.Api.csproj -p:PublishProfile=FolderProfile  --configuration Release --output public
      - name: Upload EmployeeHR.Api build artifact
        uses: actions/upload-artifact@master
        with:
          name: dotnet artifacts
          path: public/

  test-artifacts:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Download EmployeeHR.Api published artifact
        uses: actions/download-artifact@master
        with:
          name: download artifacts
          path: public
