name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Upload EmployeeHR.Api build artifact
        uses: actions/upload-artifact@master
        with:
          name: dotnet artifacts
          path: public/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download EmployeeHR.Api build artifact
        uses: actions/download-artifact@master
        with:
          name: dotnet artifacts
          path: public

      - name: Test
        run: dotnet test EmployeeHR.LogicTests --no-build --verbosity normal
